import asyncio
from typing import Dict, Optional, Tuple, List

import discord

from src.core.agent_base import BaseAgent
from .config import load_config, InviteRoleAssignerConfig


class InviteRoleAssignerAgent(BaseAgent):
    """
    招待リンク（invite）の uses 差分から「どの招待で入ったか」を推測してロール付与するエージェント。

    仕様:
    - 招待枠URL  -> agi-lab + ログ「招待枠で参加」
    - 一般枠URL  -> agi-lab + ログ「一般枠で参加」
    - 検出失敗   -> agi-lab + 要確認 + ログ「検出失敗」
    """

    def __init__(self) -> None:
        self.cfg: InviteRoleAssignerConfig = load_config()
        self._client: Optional[discord.Client] = None
        self._guild: Optional[discord.Guild] = None

        self._invite_uses: Dict[str, int] = {}
        self._lock = asyncio.Lock()

    @property
    def name(self) -> str:
        return "InviteRoleAssignerAgent"

    async def on_ready(self, client: discord.Client) -> None:
        self._client = client
        guild = client.get_guild(self.cfg.guild_id)
        if guild is None:
            # botがまだguild情報をキャッシュできてない等もあるので fetch も試す
            try:
                guild = await client.fetch_guild(self.cfg.guild_id)
            except Exception:
                guild = None

        if guild is None:
            print(f"[{self.name}] ERROR: guild not found in cache/fetch. guild_id={self.cfg.guild_id}")
            return

        self._guild = guild

        # ベースライン（現在の招待 uses）を取得
        await self._refresh_invites_baseline(reason="startup")

        await self._log(f"✅ {self.name} ready. invited_codes={len(self.cfg.invited_codes)}")

    async def on_message(self, message: discord.Message) -> None:
        # Bot自身のメッセージは無視
        if message.author.bot:
            return

        # 対象Guildのみ
        if not message.guild or message.guild.id != self.cfg.guild_id:
            return

        # 管理コマンド: !invrole generate
        content = message.content.strip()
        if content == "!invrole generate":
            await self._cmd_generate_expert_invites(message)
            return

        if content == "!invrole delete_all":
            await self._cmd_delete_all_invites(message)
            return

        if content == "!invrole test":
            await self._cmd_generate_test_invite(message)
            return

        if content == "!invrole status":
            await self._cmd_status(message)
            return

        if content == "!invrole help":
            await message.channel.send(
                "**InviteRoleAssigner Commands**\n"
                "• `!invrole status` - システム状態を一括チェック\n"
                "• `!invrole generate` - 招待枠・一般枠の招待URL各1本を生成\n"
                "• `!invrole test` - テスト用招待リンク1本を生成\n"
                "• `!invrole delete_all` - Bot作成の招待リンクを全削除\n"
                "• `!invrole help` - このヘルプを表示"
            )
            return

    async def _cmd_generate_expert_invites(self, message: discord.Message) -> None:
        """招待枠・一般枠の招待URL各1本を生成し、ログチャンネルに出力"""
        # 権限チェック: 管理者ロールを持っているか
        member = message.author
        if not isinstance(member, discord.Member):
            return

        admin_role = message.guild.get_role(self.cfg.admin_role_id)
        if admin_role is None or admin_role not in member.roles:
            await message.channel.send("❌ このコマンドは管理者のみ実行できます。")
            return

        # 招待リンクを作成するチャンネル（コマンド実行チャンネル）
        channel = message.channel
        if not isinstance(channel, discord.TextChannel):
            await message.channel.send("❌ テキストチャンネルで実行してください。")
            return

        await message.channel.send("🔄 招待URL（招待枠・一般枠）を生成中（無期限・無制限）...")

        try:
            # 招待枠URL
            invited_invite = await channel.create_invite(
                max_age=0,       # 無期限
                max_uses=0,      # 無制限
                unique=True,
                reason="招待枠 invite generated by InviteRoleAssigner"
            )
            # 一般枠URL
            general_invite = await channel.create_invite(
                max_age=0,       # 無期限
                max_uses=0,      # 無制限
                unique=True,
                reason="一般枠 invite generated by InviteRoleAssigner"
            )
        except discord.Forbidden:
            await message.channel.send(
                "❌ 招待リンクの作成に失敗しました（Forbidden）。Botに **Create Invite** 権限が必要です。"
            )
            return
        except Exception as e:
            await message.channel.send(f"❌ 招待リンクの作成に失敗: {type(e).__name__}: {e}")
            return

        result_msg = (
            f"✅ **招待URLを生成しました** (無期限・無制限)\n\n"
            f"**招待枠URL** (QRコード用):\n{invited_invite.url}\n"
            f"コード: `{invited_invite.code}`\n\n"
            f"**一般枠URL** (QRコード用):\n{general_invite.url}\n"
            f"コード: `{general_invite.code}`\n\n"
            f"**`.env`用 (コピペ用):**\n```\nINVROLE_INVITED_CODES={invited_invite.code}\n```"
        )

        await self._log(result_msg)

        # ベースライン更新（新しい招待が追加されたので）
        await self._refresh_invites_baseline(reason="after_generate")

        await message.channel.send("✅ 完了！ログチャンネルに出力しました。")

    async def _cmd_generate_test_invite(self, message: discord.Message) -> None:
        """テスト用招待リンク1本を生成"""
        # 権限チェック: 管理者ロールを持っているか
        member = message.author
        if not isinstance(member, discord.Member):
            return

        admin_role = message.guild.get_role(self.cfg.admin_role_id)
        if admin_role is None or admin_role not in member.roles:
            await message.channel.send("❌ このコマンドは管理者のみ実行できます。")
            return

        channel = message.channel
        if not isinstance(channel, discord.TextChannel):
            await message.channel.send("❌ テキストチャンネルで実行してください。")
            return

        try:
            invite = await channel.create_invite(
                max_age=0,
                max_uses=0,  # 無制限（差分検出のため）
                unique=True,
                reason="Test invite generated by InviteRoleAssigner"
            )
            await message.channel.send(
                f"✅ テスト用招待リンク:\n{invite.url}\n"
                f"コード: `{invite.code}`"
            )
            await self._log(f"🧪 テスト招待生成: `{invite.code}` by {member}")
            await self._refresh_invites_baseline(reason="after_test_generate")
        except discord.Forbidden:
            await message.channel.send("❌ 招待リンクの作成に失敗しました（Forbidden）。")
        except Exception as e:
            await message.channel.send(f"❌ 招待リンクの作成に失敗: {type(e).__name__}: {e}")

    async def _cmd_delete_all_invites(self, message: discord.Message) -> None:
        """Bot が作成した招待リンクを全削除"""
        # 権限チェック: 管理者ロールを持っているか
        member = message.author
        if not isinstance(member, discord.Member):
            return

        admin_role = message.guild.get_role(self.cfg.admin_role_id)
        if admin_role is None or admin_role not in member.roles:
            await message.channel.send("❌ このコマンドは管理者のみ実行できます。")
            return

        guild = self._guild
        if guild is None:
            await message.channel.send("❌ Guildが見つかりません。")
            return

        await message.channel.send("🔄 招待リンクを削除中...")

        try:
            invites = await guild.invites()
        except discord.Forbidden:
            await message.channel.send("❌ 招待一覧の取得に失敗しました（Forbidden）。")
            return
        except Exception as e:
            await message.channel.send(f"❌ 招待一覧の取得に失敗: {type(e).__name__}: {e}")
            return

        # Bot が作成した招待のみ削除
        bot_user = self._client.user
        deleted_count = 0
        failed_count = 0

        for invite in invites:
            if invite.inviter and invite.inviter.id == bot_user.id:
                try:
                    await invite.delete(reason="Deleted by !invrole delete_all command")
                    deleted_count += 1
                except Exception:
                    failed_count += 1

        # ベースライン更新
        await self._refresh_invites_baseline(reason="after_delete_all")

        result = f"✅ 削除完了: {deleted_count}件"
        if failed_count > 0:
            result += f" (失敗: {failed_count}件)"
        await message.channel.send(result)
        await self._log(f"🗑️ 招待リンク削除: {deleted_count}件削除 by {member}")

    async def _cmd_status(self, message: discord.Message) -> None:
        """システム状態を一括チェック"""
        guild = message.guild
        results: List[str] = []
        all_ok = True

        # 1. Bot接続
        if self._client and self._client.is_ready():
            results.append("✅ Bot接続: OK")
        else:
            results.append("❌ Bot接続: NG")
            all_ok = False

        # 2. Guild
        if self._guild:
            results.append(f"✅ Guild: {self._guild.name}")
        else:
            results.append("❌ Guild: 未取得")
            all_ok = False

        # 3. agi-lab ロール
        general_role = guild.get_role(self.cfg.general_role_id)
        if general_role:
            results.append(f"✅ agi-lab ロール: {general_role.name}")
        else:
            results.append(f"❌ agi-lab ロール: 見つからない (ID: {self.cfg.general_role_id})")
            all_ok = False

        # 4. 要確認ロール
        review_role = guild.get_role(self.cfg.review_role_id)
        if review_role:
            results.append(f"✅ 要確認ロール: {review_role.name}")
        else:
            results.append(f"❌ 要確認ロール: 見つからない (ID: {self.cfg.review_role_id})")
            all_ok = False

        # 5. 管理者ロール
        admin_role = guild.get_role(self.cfg.admin_role_id)
        if admin_role:
            results.append(f"✅ 管理者ロール: {admin_role.name}")
        else:
            results.append(f"❌ 管理者ロール: 見つからない (ID: {self.cfg.admin_role_id})")
            all_ok = False

        # 6. ログチャンネル
        log_ch = self._client.get_channel(self.cfg.log_channel_id)
        if log_ch:
            results.append(f"✅ ログチャンネル: #{log_ch.name}")
        else:
            results.append(f"❌ ログチャンネル: 見つからない (ID: {self.cfg.log_channel_id})")
            all_ok = False

        # 7. 招待枠コード設定
        if self.cfg.invited_codes:
            results.append(f"✅ 招待枠コード: {len(self.cfg.invited_codes)}個設定済み")
            for code in self.cfg.invited_codes:
                results.append(f"   • `{code}`")
        else:
            results.append("⚠️ 招待枠コード: 未設定（全員「一般枠」になります）")

        # 8. ベースライン招待
        results.append(f"✅ 監視中の招待: {len(self._invite_uses)}個")

        # 9. 招待枠コードがサーバーに存在するかチェック
        if self.cfg.invited_codes:
            missing_codes = [c for c in self.cfg.invited_codes if c not in self._invite_uses]
            if missing_codes:
                results.append(f"⚠️ 招待枠コードがサーバーに存在しません: {', '.join(missing_codes)}")
                all_ok = False
            else:
                results.append("✅ 招待枠コード: サーバーに存在確認済み")

        # 結果出力
        status_emoji = "✅" if all_ok else "⚠️"
        header = f"**{status_emoji} InviteRoleAssigner ステータス**\n"
        await message.channel.send(header + "\n".join(results))

        # ログチャンネルにもテスト送信
        if log_ch and all_ok:
            try:
                await log_ch.send("🔧 ステータスチェック: 正常動作中")
                await message.channel.send(f"\n📝 `#{log_ch.name}` にテストログを送信しました")
            except Exception as e:
                await message.channel.send(f"\n❌ ログチャンネルへの送信に失敗: {e}")

    async def _refresh_invites_baseline(self, reason: str) -> None:
        guild = self._guild
        if guild is None:
            return
        try:
            invites = await guild.invites()  # requires MANAGE_GUILD
            self._invite_uses = {inv.code: (inv.uses or 0) for inv in invites}
            if self.cfg.debug:
                await self._log(f"🔄 Baseline refreshed ({reason}). invites={len(self._invite_uses)}")
        except discord.Forbidden:
            await self._log(
                "❌ 招待一覧の取得に失敗しました（Forbidden）。Botに **Manage Server(Manage Guild)** 権限が必要です。"
            )
        except Exception as e:
            await self._log(f"❌ 招待一覧の取得に失敗: {type(e).__name__}: {e}")

    async def on_member_join(self, member: discord.Member) -> None:
        # デバッグ: イベント発火確認
        if self.cfg.debug:
            print(f"[{self.name}] DEBUG: on_member_join fired for {member} in guild {member.guild.id}")

        # 目的のguildのみ
        if member.guild.id != self.cfg.guild_id:
            if self.cfg.debug:
                print(f"[{self.name}] DEBUG: guild mismatch, skipping. expected={self.cfg.guild_id}")
            return

        if self.cfg.debug:
            print(f"[{self.name}] DEBUG: processing member join...")

        async with self._lock:
            used_code, debug_detail = await self._detect_used_invite_code(member.guild)

            # ロール取得
            general_role = member.guild.get_role(self.cfg.general_role_id)
            review_role = member.guild.get_role(self.cfg.review_role_id)

            # 付与するロール
            roles_to_add: List[discord.Role] = []
            if general_role:
                roles_to_add.append(general_role)

            # 招待タイプ判定
            if used_code in self.cfg.invited_codes:
                invite_type = "招待枠"
            elif used_code:
                invite_type = "一般枠"
            else:
                invite_type = "検出失敗"
                # 検出失敗時は要確認ロールも付与
                if review_role:
                    roles_to_add.append(review_role)

            # ロール付与
            if roles_to_add:
                try:
                    await member.add_roles(*roles_to_add, reason=f"InviteRoleAssigner: {invite_type}")
                except Exception as e:
                    await self._log(f"❌ ロール付与失敗: {member.mention} - {type(e).__name__}: {e}")

            # ログ出力
            code_str = used_code if used_code else "UNKNOWN"
            role_names = ", ".join([r.name for r in roles_to_add]) if roles_to_add else "なし"
            msg = (
                f"👤 {member.mention} (`{member.id}`) - **{invite_type}**\n"
                f"• invite: `{code_str}`\n"
                f"• roles: {role_names}"
            )
            if self.cfg.debug:
                msg += f"\n• debug: {debug_detail}"

            await self._log(msg)

            # 最後にベースライン更新（次のjoinに備える）
            await self._refresh_invites_baseline(reason="after_join")

    async def _detect_used_invite_code(self, guild: discord.Guild) -> Tuple[Optional[str], str]:
        """
        直前ベースライン(self._invite_uses)と現在の招待 uses を比較し、
        使われた可能性が高い invite code を返す。

        改善点:
        - リトライ機能: 招待usesが反映されるまで0.8秒→1.6秒でリトライ
        - 消えた招待の検出: max_uses=1で使用後に消えた招待を検出

        戻り値: (used_code or None, debug_detail)
        """
        prev = self._invite_uses or {}

        # リトライ付きで招待一覧を取得・比較
        retry_delays = [0, 0.8, 1.6]  # 初回、0.8秒後、1.6秒後
        last_debug_detail = ""

        for attempt, delay in enumerate(retry_delays):
            if delay > 0:
                await asyncio.sleep(delay)

            try:
                invites = await guild.invites()
                current = {inv.code: (inv.uses or 0) for inv in invites}
            except discord.Forbidden:
                return None, "Forbidden while fetching invites"
            except Exception as e:
                return None, f"Error while fetching invites: {type(e).__name__}: {e}"

            # 増加した招待を検出
            changes: List[Tuple[str, int, int]] = []  # (code, prev_uses, curr_uses)
            for code, curr_uses in current.items():
                prev_uses = prev.get(code, 0)
                if curr_uses > prev_uses:
                    changes.append((code, prev_uses, curr_uses))

            # 消えた招待を検出（max_uses=1で使い切られた場合）
            vanished: List[str] = []
            for code in prev.keys():
                if code not in current:
                    vanished.append(code)

            # デバッグ情報
            debug_parts = []
            if changes:
                debug_parts.append("changes=" + ", ".join([f"{c}:{p}->{n}" for c, p, n in changes]))
            else:
                debug_parts.append("changes=none")
            if vanished:
                debug_parts.append("vanished=" + ", ".join(vanished))
            if attempt > 0:
                debug_parts.append(f"retry={attempt}")
            last_debug_detail = "; ".join(debug_parts)

            # 判定ロジック（優先順位順）

            # 1. 増加が1件かつ+1 → それを採用
            if len(changes) == 1 and (changes[0][2] - changes[0][1]) == 1:
                return changes[0][0], last_debug_detail

            # 2. 増加がなく、消えた招待が1件だけ → それを採用
            if len(changes) == 0 and len(vanished) == 1:
                return vanished[0], last_debug_detail

            # それ以外はリトライを続ける（最後のループでは諦める）

        # すべてのリトライで検出できなかった
        return None, last_debug_detail

    async def _log(self, content: str) -> None:
        if not self._client:
            print(f"[{self.name}] {content}")
            return
        ch = self._client.get_channel(self.cfg.log_channel_id)
        if ch is None:
            # fetchも試す
            try:
                ch = await self._client.fetch_channel(self.cfg.log_channel_id)
            except Exception:
                ch = None

        if isinstance(ch, (discord.TextChannel, discord.Thread)):
            try:
                await ch.send(content)
            except Exception:
                print(f"[{self.name}] Failed to send log. content={content}")
        else:
            print(f"[{self.name}] Log channel not found. content={content}")
